-- ADAPTA — datos de demostración
--
-- Generado desde `frontend/src/services/mocks/` para que la base y los mocks
-- del frontend digan exactamente lo mismo. Si cambiás uno, regenerá el otro.
--
-- AVISO: los 8 negocios son FICTICIOS. Ninguno corresponde a una empresa,
-- taller o clínica real. Las ubicaciones y los rangos de precio sí son
-- realistas, para que la demo no se vea de juguete.
--
-- El catálogo está diseñado para producir diferencias VISIBLES de
-- compatibilidad: hay productos muy adaptados, uno convencional que solo
-- sirve tras adaptación, y varios intermedios. Si cambiás los datos, la demo
-- deja de ser predecible.
--
-- Aplicar después de `schema.sql`. Se puede volver a ejecutar.

truncate adaptation_requests, product_adaptation_needs, products, providers restart identity cascade;

-- ---------------------------------------------------------------------------
-- Negocios inscritos (8)
-- ---------------------------------------------------------------------------

insert into providers
  (id, name, kind, description, location, ships_nationwide,
   contact_website, contact_phone, contact_email, plan, verified)
values
  ('prv-001', 'Vera Studio', 'adaptive-apparel',
   'Taller de confección especializado en camisería con cierre magnético. Producción propia y ajuste a medida.',
   'San José, Costa Rica', true,
   'https://ejemplo.test/vera', '+506 0000 0001', null,
   'featured', true),
  ('prv-002', 'Ronda Adaptive', 'adaptive-apparel',
   'Pantalones y faldas con apertura lateral, pensados para vestirse sentado. Catálogo por talla extendida.',
   'Heredia, Costa Rica', true,
   'https://ejemplo.test/ronda', null, 'hola@ejemplo.test',
   'verified', true),
  ('prv-003', 'Taller Puntada Abierta', 'adaptation-workshop',
   'Modifican ropa que ya tenés: cambian botones por imanes, abren costuras, quitan etiquetas y añaden argollas de tiro.',
   'Cartago, Costa Rica', false,
   null, '+506 0000 0003', null,
   'verified', true),
  ('prv-004', 'Ortopedia Meseta', 'prosthetics',
   'Prótesis de miembro superior e inferior, órtesis a medida y mantenimiento. Valoración presencial requerida.',
   'San José, Costa Rica', false,
   'https://ejemplo.test/meseta', '+506 0000 0004', null,
   'featured', true),
  ('prv-005', 'Movilidad Norte', 'mobility-aids',
   'Sillas de ruedas manuales y eléctricas, andaderas y bastones. Alquiler y venta.',
   'Alajuela, Costa Rica', true,
   'https://ejemplo.test/norte', null, null,
   'free', false),
  ('prv-006', 'Cotidiano', 'daily-living-aids',
   'Utensilios de agarre grueso, abotonadores, calzadores largos y productos de apoyo para la vida diaria.',
   'Puntarenas, Costa Rica', true,
   null, null, 'contacto@ejemplo.test',
   'free', false),
  ('prv-007', 'Calma Textil', 'adaptive-apparel',
   'Tejido sin costuras para sensibilidad sensorial. Prendas de una sola pieza en algodón orgánico.',
   'San José, Costa Rica', true,
   'https://ejemplo.test/calma', null, null,
   'verified', true),
  ('prv-008', 'Lienzo', 'adaptive-apparel',
   'Camisería clásica de confección tradicional. Listada porque su ropa es candidata frecuente a adaptación.',
   'San José, Costa Rica', false,
   'https://ejemplo.test/lienzo', null, null,
   'free', false);

-- ---------------------------------------------------------------------------
-- Catálogo (14)
-- ---------------------------------------------------------------------------

insert into products
  (id, provider_id, name, brand, category, price, currency, description,
   closure_type, materials, limitations, sizes, images, in_stock)
values
  ('adp-001', 'prv-001', 'Camisa Vera de cierre magnético', 'Vera Studio',
   'tops', 42000, 'CRC',
   'Camisa de popelina con botones decorativos sobre cierre magnético oculto. Se abrocha con una sola mano y sin pinza fina.',
   'magnetic',
   array['Algodón 97%', 'Elastano 3%']::text[],
   array['Los imanes pueden interferir con marcapasos y desfibriladores: consultá con tu equipo de salud antes de usarla.']::text[],
   array['S', 'M', 'L', 'XL']::text[],
   '[{"url":"/products/camisa-vera.svg","alt":"Camisa celeste de manga larga con botonadura frontal recta"}]'::jsonb, true),
  ('adp-002', 'prv-002', 'Pantalón Ronda de apertura lateral', 'Ronda',
   'bottoms', 51000, 'CRC',
   'Pantalón con cierre lateral completo de cadera a tobillo. Permite vestirse sentado o acostado sin levantar las caderas.',
   'zipper-loop',
   array['Poliéster reciclado 65%', 'Algodón 32%', 'Elastano 3%']::text[],
   array['La apertura lateral requiere destreza para alinear el cierre; con agarre muy limitado conviene la versión de velcro.']::text[],
   array['S', 'M', 'L', 'XL', 'XXL']::text[],
   '[{"url":"/products/pantalon-ronda.svg","alt":"Pantalón gris recto con costura lateral marcada de arriba abajo"}]'::jsonb, true),
  ('adp-003', 'prv-002', 'Tenis Paso sin cordones', 'Paso',
   'footwear', 68000, 'CRC',
   'Calzado con talón abatible y cierre elástico. Se calza empujando el pie, sin manos y sin agacharse.',
   'elastic',
   array['Malla técnica', 'Suela de caucho']::text[],
   array['La horma estándar no acomoda órtesis de tobillo voluminosas.']::text[],
   array['36', '38', '40', '42', '44']::text[],
   '[{"url":"/products/tenis-paso.svg","alt":"Tenis blanco y verde de perfil, con talón reforzado"}]'::jsonb, true),
  ('adp-004', 'prv-007', 'Buzo Calma sin costuras', 'Calma',
   'tops', 39000, 'CRC',
   'Buzo tejido en una sola pieza, sin costuras internas ni etiquetas, con puños anchos que no aprietan.',
   'none',
   array['Algodón orgánico 90%', 'Elastano 10%']::text[],
   array['Al ser cerrado por la cabeza, no sirve si no podés levantar los brazos.']::text[],
   array['XS', 'S', 'M', 'L', 'XL']::text[],
   '[{"url":"/products/buzo-calma.svg","alt":"Buzo beige de cuello redondo, superficie lisa sin costuras visibles"}]'::jsonb, true),
  ('adp-005', 'prv-002', 'Chaqueta Norte con acceso de brazo', 'Norte',
   'outerwear', 87000, 'CRC',
   'Chaqueta impermeable con aperturas de hombro a muñeca en ambos brazos, pensada para vestirse sentado sin sacar el brazo.',
   'zipper-loop',
   array['Nylon reciclado', 'Membrana impermeable']::text[],
   array['Es más pesada que una chaqueta convencional por las aperturas reforzadas.']::text[],
   array['S', 'M', 'L', 'XL']::text[],
   '[{"url":"/products/chaqueta-norte.svg","alt":"Chaqueta azul marino con capucha y cierres verticales en las mangas"}]'::jsonb, false),
  ('adp-006', 'prv-008', 'Camisa Clásica de botón', 'Lienzo',
   'tops', 28000, 'CRC',
   'Camisa de vestir convencional, con botonadura tradicional y puño abotonado. Incluida como referencia de lo que hoy existe en tienda.',
   'buttons',
   array['Algodón 100%']::text[],
   array['Requiere pinza fina y dos manos. Es candidata a adaptación, no a uso directo.']::text[],
   array['S', 'M', 'L', 'XL']::text[],
   '[{"url":"/products/camisa-clasica.svg","alt":"Camisa blanca de vestir con botones tradicionales"}]'::jsonb, true),
  ('adp-007', 'prv-002', 'Falda Vuelta con velcro', 'Vuelta',
   'bottoms', 34000, 'CRC',
   'Falda cruzada que se cierra con dos bandas anchas de velcro. Se coloca por delante estando sentada.',
   'velcro',
   array['Lino 60%', 'Viscosa 40%']::text[],
   array['El velcro engancha tejidos delicados; conviene cerrarlo antes de lavar.']::text[],
   array['S', 'M', 'L']::text[],
   '[{"url":"/products/falda-vuelta.svg","alt":"Falda verde oliva cruzada, con solapa frontal"}]'::jsonb, true),
  ('adp-008', 'prv-007', 'Camiseta Puerto con puerto de acceso', 'Puerto',
   'tops', 31000, 'CRC',
   'Camiseta con dos aperturas discretas en el pecho, cerradas con solapa, para acceso a catéter o puerto sin desvestirse.',
   'velcro',
   array['Modal 95%', 'Elastano 5%']::text[],
   array['Las solapas son visibles bajo tejidos muy finos o de color claro.']::text[],
   array['XS', 'S', 'M', 'L', 'XL']::text[],
   '[{"url":"/products/camiseta-puerto.svg","alt":"Camiseta gris de manga corta con dos solapas discretas en el pecho"}]'::jsonb, true),
  ('adp-009', 'prv-004', 'Prótesis mioeléctrica de mano', 'Ortopedia Meseta',
   'prosthetics', 4200000, 'CRC',
   'Prótesis de mano accionada por señales musculares del antebrazo. Incluye valoración, molde, ajuste y tres sesiones de entrenamiento.',
   'none',
   array['Fibra de carbono', 'Silicona médica']::text[],
   array['Requiere valoración presencial: no se puede encargar en línea.', 'El precio varía según el nivel de amputación y la cobertura del seguro.']::text[],
   array['A medida']::text[],
   '[{"url":"/products/protesis-mano.svg","alt":"Prótesis de mano de color gris con articulaciones en los dedos"}]'::jsonb, true),
  ('adp-010', 'prv-004', 'Órtesis de tobillo y pie', 'Ortopedia Meseta',
   'orthotics', 310000, 'CRC',
   'Órtesis termoconformada que estabiliza el tobillo y corrige el pie caído al caminar. Se usa dentro del calzado.',
   'velcro',
   array['Polipropileno', 'Forro de espuma']::text[],
   array['Necesita calzado de horma ancha y profundidad extra: no entra en un tenis estándar.']::text[],
   array['A medida']::text[],
   '[{"url":"/products/ortesis-tobillo.svg","alt":"Órtesis blanca en forma de L que cubre la pantorrilla y la planta del pie"}]'::jsonb, true),
  ('adp-011', 'prv-005', 'Silla de ruedas manual ultraligera', 'Movilidad Norte',
   'mobility', 890000, 'CRC',
   'Chasis rígido de aluminio de 9 kg, respaldo regulable y ejes de liberación rápida para meterla al carro.',
   'none',
   array['Aluminio aeronáutico', 'Tapicería de nylon']::text[],
   array['El chasis rígido no se pliega: se desarma en piezas para transportarla.', 'Requiere fuerza de brazos para autopropulsarse en cuesta.']::text[],
   array['38 cm', '40 cm', '45 cm']::text[],
   '[{"url":"/products/silla-ultraligera.svg","alt":"Silla de ruedas de chasis azul con ruedas traseras grandes inclinadas"}]'::jsonb, true),
  ('adp-012', 'prv-006', 'Abotonador de mango grueso', 'Cotidiano',
   'daily-living', 9500, 'CRC',
   'Gancho de alambre con mango de 3 cm de diámetro. Pasa el botón por el ojal con una sola mano y sin pinza fina.',
   'none',
   array['Acero inoxidable', 'Mango de espuma']::text[],
   array['Sirve para botones medianos y grandes. Con botones muy pequeños sigue siendo difícil.']::text[],
   array['Talla única']::text[],
   '[{"url":"/products/abotonador.svg","alt":"Utensilio con mango grueso de color naranja y gancho de alambre en la punta"}]'::jsonb, true),
  ('adp-013', 'prv-006', 'Calzador de mango largo', 'Cotidiano',
   'daily-living', 7800, 'CRC',
   'Calzador de 60 cm con mango curvo. Permite ponerse el zapato sentado, sin agacharse ni doblar la cadera.',
   'none',
   array['Aluminio anodizado']::text[],
   array['No sustituye un calzado sin cordones: solo ayuda a meter el pie.']::text[],
   array['60 cm']::text[],
   '[{"url":"/products/calzador.svg","alt":"Calzador metálico largo con mango curvo en un extremo"}]'::jsonb, true),
  ('adp-014', 'prv-003', 'Servicio de adaptación de prenda propia', 'Taller Puntada Abierta',
   'accessories', 15000, 'CRC',
   'Llevás una prenda que ya tenés y la modifican: cambio de botones por imanes, apertura de costura lateral, retiro de etiquetas o argolla de tiro. Precio desde, según el trabajo.',
   'none',
   array['Depende de la prenda']::text[],
   array['Atención solo presencial en Cartago: hay que llevar la prenda al taller.', 'Algunas modificaciones no se pueden revertir sin dejar marca.']::text[],
   array['La de tu prenda']::text[],
   '[{"url":"/products/servicio-adaptacion.svg","alt":"Máquina de coser con una prenda en proceso de modificación"}]'::jsonb, true);

-- ---------------------------------------------------------------------------
-- Qué necesidad cubre cada producto (44 relaciones)
--
-- Ojo: adp-006 (camisa clásica) no aparece acá a propósito. Es la prenda
-- convencional que solo encaja tras una adaptación, y sirve para demostrar
-- que el motor distingue.
-- ---------------------------------------------------------------------------

insert into product_adaptation_needs (product_id, need)
values
  ('adp-001', 'one-handed-dressing'),
  ('adp-001', 'magnetic-closure'),
  ('adp-001', 'no-fine-motor'),
  ('adp-001', 'seated-wearing'),
  ('adp-002', 'seated-wearing'),
  ('adp-002', 'easy-access-medical'),
  ('adp-002', 'adjustable-fit'),
  ('adp-003', 'one-handed-dressing'),
  ('adp-003', 'no-fine-motor'),
  ('adp-003', 'seated-wearing'),
  ('adp-003', 'adjustable-fit'),
  ('adp-004', 'sensory-friendly'),
  ('adp-004', 'no-fine-motor'),
  ('adp-004', 'thermoregulation'),
  ('adp-004', 'seated-wearing'),
  ('adp-005', 'seated-wearing'),
  ('adp-005', 'easy-access-medical'),
  ('adp-005', 'one-handed-dressing'),
  ('adp-005', 'prosthesis-friendly'),
  ('adp-007', 'seated-wearing'),
  ('adp-007', 'one-handed-dressing'),
  ('adp-007', 'no-fine-motor'),
  ('adp-007', 'adjustable-fit'),
  ('adp-008', 'easy-access-medical'),
  ('adp-008', 'sensory-friendly'),
  ('adp-008', 'seated-wearing'),
  ('adp-008', 'no-fine-motor'),
  ('adp-009', 'prosthesis-friendly'),
  ('adp-009', 'one-handed-dressing'),
  ('adp-009', 'adjustable-fit'),
  ('adp-010', 'prosthesis-friendly'),
  ('adp-010', 'adjustable-fit'),
  ('adp-011', 'seated-wearing'),
  ('adp-011', 'adjustable-fit'),
  ('adp-012', 'one-handed-dressing'),
  ('adp-012', 'no-fine-motor'),
  ('adp-013', 'seated-wearing'),
  ('adp-013', 'one-handed-dressing'),
  ('adp-013', 'no-fine-motor'),
  ('adp-014', 'magnetic-closure'),
  ('adp-014', 'no-fine-motor'),
  ('adp-014', 'sensory-friendly'),
  ('adp-014', 'seated-wearing'),
  ('adp-014', 'easy-access-medical');
